export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
}

export default function RootLayout({
  children
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <h1>LOGIN LAYOUT</h1>
      <body>{children}</body>
    </html>
  )
}
